# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5da453eeeddd2723ee785948168335e36742cdbb2f0f4c37cd399fce1e987c650591c312916ce5444bd9097eac5d1d3635ef9843d435248fd6650a1cbde6a53

test:
  secret_key_base: 7f91bb89fbbbaf440c18f3727b40a04a1782997c527a210fd11dd6e6ed2015bc8945f81b94bb2e0814ff5bd5f42d3ffb5d070e71c5c286600ae4b7c7bbe0a8f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
